### ISSUE TITLE
Get stuck on " Checking pubg.report now! "

### ISSUE THREAD

**Issue by d2Ok** [kragebein/pubg.reportbot#1]
Hello, i discover your discord bot for pubg.report recently, i very cool bot ! i'm love it..

But i test install on my dedicaced server & local computer, i'm get stuck on " Checking pubg.report now! ", no response on discord and nothing happen ( database.db is empty...) - i'm newby on python and programming...

Dedicated server (debian10): - Python 3.7.3 [ requests  2.21.0 - discord.py 1.3.3 ]
Local computeur (windows10) : - Python 3.8.2 [ requests 2.23.0 - discord.py 1.3.3 ]

Do you have any idea where i could get stuck?

Thanks for your work man !

**Comment by kragebein** [comment]
Hey. have your registered your users? 
If it can't find anything it'll just say "Checking pubg.report now!".

**Comment by d2Ok** [comment]
Hello,
I tested the different commands in the discord channel where the webhook is generated:
-" !register doOk " : nothing happens.
-" !test doOk " : nothing happens either.

I also controlled the API key of Discord and the url of the webhook, it seems good to me on this side.
![pubgbot py](https://user-images.githubusercontent.com/18532040/81104318-9f1eca80-8f12-11ea-8e1d-e34822453290.png)

I checked the database.db, it remains empty. No user registered in it.

I'm lost. Thank you for your reply  !

**Comment by donutz10** [comment]
File "c:/Users/Ali/Desktop/pubg.reportbot-master/pubgbot.py", line 6, in <module>
    from bot.main import client as client
  File "c:\Users\Ali\Desktop\pubg.reportbot-master\main.py", line 86, in <module>
    checkforupdate()
  File "c:\Users\Ali\Desktop\pubg.reportbot-master\main.py", line 63, in checkforupdate
    with open('version.txt', 'r') as versions:
FileNotFoundError: [Errno 2] No such file or directory: 'version.txt'
The directory remains as is, I only changed the token and the Webhook URL. How do I fix this?

**Comment by kragebein** [comment]
Did you remove the file version.txt ?  its supposed to get downloaded when you clone the repo.

**Comment by donutz10** [comment]
I have removed the file and managed to get the bot fixed, but this shows up.
Traceback (most recent call last):
  File "c:\Users\Ali\Desktop\pubg.reportbot-master\bot\paralell.py", line 68, in main
    api.event(pubgname, discord) # Run the results through pubg.report api
  File "c:\Users\Ali\Desktop\pubg.reportbot-master\bot\pubg.py", line 51, in event
    self.build_embed(discorduser=discorduser, killer=killer, victim=victim, distance=distance, mmap=mmap, mode=mode, weapon=weapon, event=event, twitchID=twitchID, videoID=videoID, matchID=matchID, eventID=eventID, when=when, diff=diff)
  File "c:\Users\Ali\Desktop\pubg.reportbot-master\bot\main.py", line 149, in build_embed
    about = compute(victim=victim, matchid=matchID)
  File "c:\Users\Ali\Desktop\pubg.reportbot-master\bot\api.py", line 35, in compute
    for i in proc['included']:
The bot works fine and auto restarts

**Comment by donutz10** [comment]
File "/Users/N/Desktop/pubg/bot/paralell.py", line 68, in main
    api.event(pubgname, discord) # Run the results through pubg.report api
  File "/Users/N/Desktop/pubg/bot/pubg.py", line 51, in event
    self.build_embed(discorduser=discorduser, killer=killer, victim=victim, distance=distance, mmap=mmap, mode=mode, weapon=weapon, event=event, twitchID=twitchID, videoID=videoID, matchID=matchID, eventID=eventID, when=when, diff=diff)
  File "/Users/Nf/Desktop/pubg/bot/main.py", line 154, in build_embed
    about = compute(victim=victim, matchid=matchID)
  File "/Users/N/Desktop/pubg/bot/api.py", line 35, in compute
    for i in proc['included']:
I managed to get everything working, I did in the terminal cd Desktop/pubg and the error message for the version fixed. But this is a new error, any idea how to fix it?
Thanks for the bot.

**Comment by donutz10** [comment]
`Checking pubg.report now!
Traceback (most recent call last):
  File "/Users/N/Desktop/pubg/bot/paralell.py", line 68, in main
    api.event(pubgname, discord) # Run the results through pubg.report api
  File "/Users/N/Desktop/pubg/bot/pubg.py", line 51, in event
    self.build_embed(discorduser=discorduser, killer=killer, victim=victim, distance=distance, mmap=mmap, mode=mode, weapon=weapon, event=event, twitchID=twitchID, videoID=videoID, matchID=matchID, eventID=eventID, when=when, diff=diff)
  File "/Users/N/Desktop/pubg/bot/main.py", line 154, in build_embed
    about = compute(victim=victim, matchid=matchID)
  File "/Users/N/Desktop/pubg/bot/api.py", line 35, in compute
    for i in proc['included']:
KeyError: 'included'`
Full issue

**Comment by kragebein** [comment]
PUBG has changed their API. I will try to fix this tonight.

**Comment by kragebein** [comment]
Commit 51fb977dd54f13418fd695226c3365b1f69eeb3f fixes this issue.
