### ISSUE TITLE
Since yesterday update bot is no longer posting reports (Shard ID None has stopped responding to the gateway).

### ISSUE THREAD

**Issue by Sunn91** [kragebein/pubg.reportbot#2]
Hello!

After last PUBG update, bot is no longer posting reports on Discord channel. Bot is running and it's online on Discord but on pubg report site I can see new reports and bot is not uploading in into the channel.

In nohup log I just found this line:
`WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.`

**Comment by kragebein** [comment]
PUBG has changed their API. Will try to fix this tonight.

**Comment by kragebein** [comment]
Commit 51fb977dd54f13418fd695226c3365b1f69eeb3f fixes this issue. Make sure you update discordpy to the latest version as well.
